spring:
  application:
    name: lv3-final-mission

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  sql:
    init:
      mode: never

api:
  holiday:
    secret-key: ${HOLIDAY_API_SECRET_KEY}
