spring:
  application:
    name: lv2-final-mission

  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:database

  jpa:
    show-sql: true

    properties:
      hibernate:
        format_sql: true

    hibernate:
      ddl-auto: create

    defer-datasource-initialization: true

api:
  holiday:
    secret-key: P3pO8a/vSRycTYVlaruIkzsFMtJoFmLgNc4iA/xa6hcSsczL90Zx9XDLtHFYT7BgZMWKtr6C3LKFNTmEkZctMQ==
